version: '3.5'
services:
  app:
    env_file: .env
    container_name: node_app
    build:
      dockerfile: Dockerfile
      context: .
    user: node
    volumes:
      - .:/app
      - /app/node_modules
      - /app
    ports:
      - '3000:3000'
