version: '3.5'
services:
  dev:
    env_file: .env
    container_name: node_app_dev
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app
    ports:
      - '3000:3000'
  test:
    env_file: .env
    container_name: node_app_test
    build:
      dockerfile: Dockerfile-test
      context: .
    volumes:
      - .:/app
      - /app/node_modules
      - /app
